name: llamacpp_openblas_lite

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted, Linux, ARM64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Buildx는 캐싱과 고급 기능을 위해 유지
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-openblas-lite
        tags: |
          type=raw,value=action_test
        labels: |
          org.opencontainers.image.architecture=arm64
          org.opencontainers.image.platform=linux/arm64
    
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./base_setting/docker/Dockerfile(llamacpp-OpenBLAS-Lite)
        # ARM64만 빌드 (네이티브 환경)
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # 라즈베리파이 메모리 고려한 빌드 설정
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        # 캐시 최적화 (네임스페이스 분리)
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-arm64:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-arm64:buildcache,mode=max
