name: llama.cpp docker build by Self-Hosted

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted, Linux, ARM64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-openblas-lite-arm64
        tags: |
          type=raw,value=action_test
        labels: |
          org.opencontainers.image.architecture=arm64
          org.opencontainers.image.platform=linux/arm64
    
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./base_setting/docker/Dockerfile(llamacpp-openblas-lite)
        
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILDKIT_INLINE_CACHE=1

        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-arm64:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-arm64:buildcache,mode=max
