name: llama.cpp docker build by Self-Hosted

on:
  workflow_dispatch:

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      cmake_ver: ${{ steps.cmake.outputs.version }}
      openblas_ver: ${{ steps.openblas.outputs.version }}
    steps:
      - name: Get latest CMake
        id: cmake
        run: |
          set -euo pipefail
          ver=$(curl -fsSL https://api.github.com/repos/Kitware/CMake/releases/latest \
                | jq -r .tag_name | sed 's/^v//')
          # 공백/개행/CR 제거
          ver=$(printf '%s' "$ver" | tr -d '\r\n[:space:]')
          [ -n "$ver" ] || { echo "No CMake version"; exit 1; }
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Get latest OpenBLAS
        id: openblas
        run: |
          set -euo pipefail
          ver=$(curl -fsSL https://api.github.com/repos/xianyi/OpenBLAS/releases/latest \
                | jq -r .tag_name | sed 's/^v//')
          ver=$(printf '%s' "$ver" | tr -d '\r\n[:space:]')
          [ -n "$ver" ] || { echo "No OpenBLAS version"; exit 1; }
          echo "version=$ver" >> "$GITHUB_OUTPUT"
          
      - name: Print get latest versions
        run: |
          echo "CMake version: ${{ steps.cmake.outputs.version }}"
          echo "OpenBLAS version: ${{ steps.openblas.outputs.version }}"

  build-and-push:
    needs: get-versions
    runs-on: [ self-hosted, Linux, ARM64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-openblas-lite-arm64
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.architecture=arm64
            org.opencontainers.image.platform=linux/arm64

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./base_setting/docker/Dockerfile(llamacpp-openblas-lite)
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.version.cmake=${{ needs.get-versions.outputs.cmake_ver }}
            org.opencontainers.image.version.openblas=${{ needs.get-versions.outputs.openblas_ver }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            CMAKE_VERSION=${{ needs.get-versions.outputs.cmake_ver }}
            OPENBLAS_VERSION=${{ needs.get-versions.outputs.openblas_ver }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-arm64:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/llamacpp-arm64:buildcache,mode=max
