# .github/workflows/raspi-arm.yml
name: build-and-push-arm64
on:
  push:
    branches: [main]
  pull_request:

env:
  IMAGE_NAME: <DockerHubID>/slm
  PLATFORMS: linux/arm64

jobs:
  build:
    runs-on: ubuntu-22.04          # 러너 OS 고정
    steps:
      - uses: actions/checkout@v4   # 코드 받아오기 :contentReference[oaicite:2]{index=2}
      - uses: docker/setup-qemu-action@v3
        with: { platforms: arm64 }  # QEMU arm64 등록 :contentReference[oaicite:3]{index=3}
      - uses: docker/setup-buildx-action@v3 # Buildx 생성 :contentReference[oaicite:4]{index=4}
      - uses: docker/login-action@v3        # Docker Hub 로그인 :contentReference[oaicite:5]{index=5}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5   # 빌드·푸시 :contentReference[oaicite:6]{index=6}
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            CMAKE_VERSION=4.0.2
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max :contentReference[oaicite:7]{index=7}
      - uses: aquasecurity/trivy-action@latest
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          exit-code: 1
      - uses: sigstore/cosign-installer@v3       # 서명(선택) :contentReference[oaicite:9]{index=9}
        if: ${{ success() }}
      - run: cosign sign --yes ${{ env.IMAGE_NAME }}:${{ github.sha }}
        if: ${{ success() }}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
